### ISSUE TITLE
Gtk:ERROR

### ISSUE THREAD

**Issue by SteveMoto** [linuxmint/mint-translations#3]
my setup:

System: Kernel: 4.4.0-72-generic x86_64 (64 bit gcc: 5.4.0)
Desktop: Cinnamon 3.2.7 (Gtk 3.18.9-1ubuntu3.2)
dm: mdm Distro: Linux Mint 18.1 Serena

README.me:
**********

1. Download POs from Launchpad
    -> done

2. Replace the content po-export with the content of archive downloaded
    -> done
        => 32 folders

            blueberry
            cinnamon
            cinnamon-bluetooth
            cinnamon-control-center
            cinnamon-screensaver
            folder-color-switcher
            lightdm-settings
            live-installer
            mdm
            mintbackup
            mint-common
            mintdesktop
            mintdrivers
            mintinstall
            mintlocale
            mintmenu
            mintnanny
            mintsources
            mintstick
            mintupdate
            mintupload
            mintwelcome
            nemo
            nemo-emblems
            pix
            slideshow-mint
            slideshow-mint-kde
            xed
            xedit
            xplayer
            xreader
            xviewer

        => 2.945 files                

3. Run ./check.sh
    -> first run:
        => Traceback (most recent call last):
                File "./mocheck.py", line 3, in <module>
           import polib
            ImportError: No module named polib

    -> python
        =>  Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
            [GCC 5.4.0 20160609] on linux2

    ->  install python-polib
        (This package installs the library for Python 2)
        V 1.0.7-1
        => done

    -> second run:
        => more then 100 items found
        => program abort
            ->  Error:  Mismatch Left Ring Mode #%d: [u'%d'] -- [u'%#d']
                        **
                        Gtk:ERROR:/build/gtk+3.0-PCLr8A/gtk+3.0-3.18.9/./gtk/gtkprogressbar.c:611:tick_cb: assertion failed: (priv->pulse2 > priv->pulse1)
                        ./check.sh: Zeile 1:  5632 Aborted                 ./mocheck.py -po po-export

4. Run ./sort.sh to move foreign translations to FOREIGN/
    -> done

        po-export contains:
            -> FOREIGN:
                po-export/FOREIGN/blueberry
                po-export/FOREIGN/cinnamon-translations
                po-export/FOREIGN/folder-color-switcher
                po-export/FOREIGN/lightdm-settings
                po-export/FOREIGN/mdm
                po-export/FOREIGN/nemo-emblems
                po-export/FOREIGN/pix
                po-export/FOREIGN/slideshow-mint
                po-export/FOREIGN/slideshow-mint-kde
                po-export/FOREIGN/xed
                po-export/FOREIGN/xplayer
                po-export/FOREIGN/xreader
                po-export/FOREIGN/xviewer

            -> and folders:
                po-export/live-installer
                po-export/mintbackup
                po-export/mint-common
                po-export/mintdesktop
                po-export/mintdrivers
                po-export/mintinstall
                po-export/mintlocale
                po-export/mintmenu
                po-export/mintnanny
                po-export/mintsources
                po-export/mintstick
                po-export/mintupdate
                po-export/mintupload
                po-export/mintwelcome

**Comment by clefebvre** [comment]
ImportError: No module named polib

apt install python-polib python3-polib
