### ISSUE TITLE
Replace "NIcht" by "Nicht" as you only write the first letter in capital

### ISSUE THREAD

**Issue by xnumad** [linuxmint/mint-translations#6]
https://github.com/linuxmint/mint-translations/blob/eb91ffd1148ce57a3367844c4af2276169597d4c/po-export/mintdrivers/mintdrivers-de.po#L112

**Comment by to-ba** [comment]
It is already done on launchpad.

**Comment by xnumad** [comment]
@to-ba When are launchpad updates going to be applied to this repository and when finally to Mint?

**Comment by to-ba** [comment]
I do not know how often but yesterday it was updated in the mint repository.

**Comment by xnumad** [comment]
Such as in the translations:
https://github.com/linuxmint/mint-translations/blob/6a7a1a9e7514725d8ca7298e97b482f8b5ee6f79/po-export/mintdrivers/mintdrivers-de.po#L112
